In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score   
)
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("../data/processed/cleaned_upi.csv")

In [4]:
X=df.drop(["isFraud",'nameOrig', 'nameDest'],axis=1)
y=df["isFraud"]

In [5]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


In [6]:
le = LabelEncoder()
X_train["type"] = le.fit_transform(X_train["type"])
X_test["type"] = le.transform(X_test["type"])



In [7]:
print("logistic regression")
lr_model=LogisticRegression(max_iter=1000)
lr_model.fit(X_train,y_train)
lr_pred=lr_model.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)
lr_pre = precision_score(y_test, lr_pred, average='weighted')
lr_rec = recall_score(y_test, lr_pred, average='weighted')
lr_f1 = f1_score(y_test, lr_pred, average='weighted')
lr_auc = roc_auc_score(
    y_test,
    lr_model.predict_proba(X_test)[:, 1]
)

print("\nClassification Report - Logistic Regression")
print(classification_report(y_test, lr_pred))
print("\nConfusion Matrix - Logistic Regression")
print(confusion_matrix(y_test, lr_pred))

logistic regression

Classification Report - Logistic Regression
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.91      0.48      0.63      1620

    accuracy                           1.00   1272524
   macro avg       0.95      0.74      0.81   1272524
weighted avg       1.00      1.00      1.00   1272524


Confusion Matrix - Logistic Regression
[[1270823      81]
 [    842     778]]


In [8]:
print(".........Decision Tree.........")
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

dt_acc = accuracy_score(y_test, dt_pred)
dt_pre = precision_score(y_test, dt_pred, average='weighted')
dt_rec = recall_score(y_test, dt_pred, average='weighted')
dt_f1 = f1_score(y_test, dt_pred, average='weighted')
dt_auc = roc_auc_score(
    y_test,
    dt_model.predict_proba(X_test)[:, 1]
)


print("\nClassification Report - Decision Tree")
print(classification_report(y_test, dt_pred))

print("\nConfusion Matrix - Decision Tree")
print(confusion_matrix(y_test, dt_pred))

.........Decision Tree.........

Classification Report - Decision Tree
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.91      0.88      0.89      1620

    accuracy                           1.00   1272524
   macro avg       0.95      0.94      0.95   1272524
weighted avg       1.00      1.00      1.00   1272524


Confusion Matrix - Decision Tree
[[1270758     146]
 [    200    1420]]


In [10]:
print(".........Random Forest.........")


rf_model = RandomForestClassifier(
     n_estimators=20,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)
rf_pre = precision_score(y_test, rf_pred, average='weighted')
rf_rec = recall_score(y_test, rf_pred, average='weighted')
rf_f1 = f1_score(y_test, rf_pred, average='weighted')
rf_auc = roc_auc_score(
    y_test,
    rf_model.predict_proba(X_test)[:, 1]
)


print("\nClassification Report - Random Forest")
print(classification_report(y_test, rf_pred))

print("\nConfusion Matrix - Random Forest")
print(confusion_matrix(y_test, rf_pred))

.........Random Forest.........

Classification Report - Random Forest
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.98      0.80      0.88      1620

    accuracy                           1.00   1272524
   macro avg       0.99      0.90      0.94   1272524
weighted avg       1.00      1.00      1.00   1272524


Confusion Matrix - Random Forest
[[1270874      30]
 [    332    1288]]


In [11]:
print(".........XGBoost.........")
xgb_model=XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

xgb_acc = accuracy_score(y_test, xgb_pred)
xgb_pre = precision_score(y_test, xgb_pred, average='weighted')
xgb_rec = recall_score(y_test, xgb_pred, average='weighted')
xgb_f1 = f1_score(y_test, xgb_pred, average='weighted')
xgb_auc = roc_auc_score(
    y_test,
    xgb_model.predict_proba(X_test)[:, 1]   
)


print("\nClassification Report - XGBoost")
print(classification_report(y_test, xgb_pred))

print("\nConfusion Matrix - XGBoost")
print(confusion_matrix(y_test, xgb_pred))

.........XGBoost.........

Classification Report - XGBoost
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.75      0.68      0.71      1620

    accuracy                           1.00   1272524
   macro avg       0.88      0.84      0.86   1272524
weighted avg       1.00      1.00      1.00   1272524


Confusion Matrix - XGBoost
[[1270538     366]
 [    517    1103]]


In [17]:
print(".........CatBoost.........")
cb_model = CatBoostClassifier( iterations=300,
    depth=6,
    learning_rate=0.1,
    random_state=42,
    verbose=False)
cb_model.fit(X_train, y_train)
cb_pred = cb_model.predict(X_test)

cb_acc = accuracy_score(y_test, cb_pred)
cb_pre = precision_score(y_test, cb_pred, average='weighted')
cb_rec = recall_score(y_test, cb_pred, average='weighted')
cb_f1 = f1_score(y_test, cb_pred, average='weighted')
cb_auc = roc_auc_score(
    y_test,
    cb_model.predict_proba(X_test)[:, 1]    
)


print("\nClassification Report - CatBoost")
print(classification_report(y_test, cb_pred))

print("\nConfusion Matrix - CatBoost")
print(confusion_matrix(y_test, cb_pred))

.........CatBoost.........

Classification Report - CatBoost
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1270904
           1       0.98      0.83      0.90      1620

    accuracy                           1.00   1272524
   macro avg       0.99      0.91      0.95   1272524
weighted avg       1.00      1.00      1.00   1272524


Confusion Matrix - CatBoost
[[1270873      31]
 [    277    1343]]


In [18]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "CatBoost"
    ],
    "Accuracy": [lr_acc, dt_acc, rf_acc, xgb_acc, cb_acc],
    "Precision": [lr_pre, dt_pre, rf_pre, xgb_pre, cb_pre],
    "Recall": [lr_rec, dt_rec, rf_rec, xgb_rec, cb_rec],
    "F1-Score": [lr_f1, dt_f1, rf_f1, xgb_f1, cb_f1],
    "ROC-AUC": [lr_auc, dt_auc, rf_auc, xgb_auc, cb_auc]
})

comparison = comparison.sort_values(
    by="Accuracy",
    ascending=False
)

print(comparison)

                 Model  Accuracy  Precision    Recall  F1-Score   ROC-AUC
4             CatBoost  0.999758   0.999754  0.999758  0.999748  0.999237
1        Decision Tree  0.999728   0.999724  0.999728  0.999726  0.938214
2        Random Forest  0.999716   0.999710  0.999716  0.999701  0.981362
3              XGBoost  0.999306   0.999277  0.999306  0.999289  0.909922
0  Logistic Regression  0.999275   0.999219  0.999275  0.999163  0.970006


In [ ]:
import joblib

joblib.dump(cb_model, "../models/catboost_model.pkl")
joblib.dump(le, "../models/label_encoders.pkl")  

FileNotFoundError: [Errno 2] No such file or directory: 'models/catboost_model.pkl'